# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Notepad.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QGridLayout, QMainWindow, QMenu,
    QMenuBar, QSizePolicy, QStatusBar, QTextEdit,
    QWidget)
import resorce_rc
import resorce_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(966, 566)
        icon = QIcon()
        icon.addFile(u":/icons/icons/notepad-24.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        self.actionNew_Window = QAction(MainWindow)
        self.actionNew_Window.setObjectName(u"actionNew_Window")
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionSave_As = QAction(MainWindow)
        self.actionSave_As.setObjectName(u"actionSave_As")
        self.actionfrf = QAction(MainWindow)
        self.actionfrf.setObjectName(u"actionfrf")
        self.actionPage_Setup = QAction(MainWindow)
        self.actionPage_Setup.setObjectName(u"actionPage_Setup")
        self.actionPrint = QAction(MainWindow)
        self.actionPrint.setObjectName(u"actionPrint")
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        self.actionCut = QAction(MainWindow)
        self.actionCut.setObjectName(u"actionCut")
        self.actionCopy = QAction(MainWindow)
        self.actionCopy.setObjectName(u"actionCopy")
        self.actionDelete = QAction(MainWindow)
        self.actionDelete.setObjectName(u"actionDelete")
        self.actionSearch_with_Bing = QAction(MainWindow)
        self.actionSearch_with_Bing.setObjectName(u"actionSearch_with_Bing")
        self.actionFind = QAction(MainWindow)
        self.actionFind.setObjectName(u"actionFind")
        self.actionFind_Next = QAction(MainWindow)
        self.actionFind_Next.setObjectName(u"actionFind_Next")
        self.actionReplace = QAction(MainWindow)
        self.actionReplace.setObjectName(u"actionReplace")
        self.actionSelact_All = QAction(MainWindow)
        self.actionSelact_All.setObjectName(u"actionSelact_All")
        self.actionTime_Date = QAction(MainWindow)
        self.actionTime_Date.setObjectName(u"actionTime_Date")
        self.actionWord_Wrap = QAction(MainWindow)
        self.actionWord_Wrap.setObjectName(u"actionWord_Wrap")
        self.actionFont = QAction(MainWindow)
        self.actionFont.setObjectName(u"actionFont")
        self.actionZoom_Out = QAction(MainWindow)
        self.actionZoom_Out.setObjectName(u"actionZoom_Out")
        self.actionZoom_In = QAction(MainWindow)
        self.actionZoom_In.setObjectName(u"actionZoom_In")
        self.actionZoom_Out_2 = QAction(MainWindow)
        self.actionZoom_Out_2.setObjectName(u"actionZoom_Out_2")
        self.actionRestore_Default_Zoom = QAction(MainWindow)
        self.actionRestore_Default_Zoom.setObjectName(u"actionRestore_Default_Zoom")
        self.actionView_Help = QAction(MainWindow)
        self.actionView_Help.setObjectName(u"actionView_Help")
        self.actionSend_Feedback = QAction(MainWindow)
        self.actionSend_Feedback.setObjectName(u"actionSend_Feedback")
        self.actionAbout_Notepad = QAction(MainWindow)
        self.actionAbout_Notepad.setObjectName(u"actionAbout_Notepad")
        self.actionAbout_Notepad_2 = QAction(MainWindow)
        self.actionAbout_Notepad_2.setObjectName(u"actionAbout_Notepad_2")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.textEdit = QTextEdit(self.centralwidget)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setStyleSheet(u"QTextEdit{\n"
"	border:none;border-bottom:1px solid rgb(210,210,210)\n"
"}")
        self.textEdit.setLineWidth(1)
        self.textEdit.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.textEdit.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.textEdit.setLineWrapMode(QTextEdit.NoWrap)
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 966, 22))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuFormat = QMenu(self.menubar)
        self.menuFormat.setObjectName(u"menuFormat")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuZoom = QMenu(self.menuView)
        self.menuZoom.setObjectName(u"menuZoom")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        # hide statusbar default seperator
        self.statusbar.setStyleSheet("QStatusBar::item { border: none; }")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuFormat.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionNew_Window)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPage_Setup)
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionDelete)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionSearch_with_Bing)
        self.menuEdit.addAction(self.actionFind)
        self.menuEdit.addAction(self.actionFind_Next)
        self.menuEdit.addAction(self.actionReplace)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionSelact_All)
        self.menuEdit.addAction(self.actionTime_Date)
        self.menuFormat.addAction(self.actionWord_Wrap)
        self.menuFormat.addAction(self.actionFont)
        self.menuView.addAction(self.menuZoom.menuAction())
        self.menuView.addAction(self.actionZoom_Out)
        self.menuZoom.addAction(self.actionZoom_In)
        self.menuZoom.addAction(self.actionZoom_Out_2)
        self.menuZoom.addAction(self.actionRestore_Default_Zoom)
        self.menuHelp.addAction(self.actionView_Help)
        self.menuHelp.addAction(self.actionSend_Feedback)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout_Notepad_2)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"New", None))
        self.actionNew_Window.setText(QCoreApplication.translate("MainWindow", u"New Window", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open...", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.actionSave_As.setText(QCoreApplication.translate("MainWindow", u"Save As...", None))
        self.actionfrf.setText(QCoreApplication.translate("MainWindow", u"frf", None))
        self.actionPage_Setup.setText(QCoreApplication.translate("MainWindow", u"Page Setup...", None))
        self.actionPrint.setText(QCoreApplication.translate("MainWindow", u"Print...", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
        self.actionCut.setText(QCoreApplication.translate("MainWindow", u"Cut", None))
        self.actionCopy.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
        self.actionDelete.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.actionSearch_with_Bing.setText(QCoreApplication.translate("MainWindow", u"Search with Bing..", None))
        self.actionFind.setText(QCoreApplication.translate("MainWindow", u"Find...", None))
        self.actionFind_Next.setText(QCoreApplication.translate("MainWindow", u"Find Next", None))
        self.actionReplace.setText(QCoreApplication.translate("MainWindow", u"Replace", None))
        self.actionSelact_All.setText(QCoreApplication.translate("MainWindow", u"Selact All", None))
        self.actionTime_Date.setText(QCoreApplication.translate("MainWindow", u"Time / Date", None))
        self.actionWord_Wrap.setText(QCoreApplication.translate("MainWindow", u"Word Wrap", None))
        self.actionFont.setText(QCoreApplication.translate("MainWindow", u"Font", None))
        self.actionZoom_Out.setText(QCoreApplication.translate("MainWindow", u"Status Bar", None))
        self.actionZoom_In.setText(QCoreApplication.translate("MainWindow", u"Zoom In", None))
        self.actionZoom_Out_2.setText(QCoreApplication.translate("MainWindow", u"Zoom Out", None))
        self.actionRestore_Default_Zoom.setText(QCoreApplication.translate("MainWindow", u"Restore Default Zoom", None))
        self.actionView_Help.setText(QCoreApplication.translate("MainWindow", u"View Help", None))
        self.actionSend_Feedback.setText(QCoreApplication.translate("MainWindow", u"Send Feedback", None))
        self.actionAbout_Notepad.setText(QCoreApplication.translate("MainWindow", u"About Notepad", None))
        self.actionAbout_Notepad_2.setText(QCoreApplication.translate("MainWindow", u"About Notepad", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuFormat.setTitle(QCoreApplication.translate("MainWindow", u"Format", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuZoom.setTitle(QCoreApplication.translate("MainWindow", u"Zoom", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
    # retranslateUi

